[project]
name = "fetching-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "pydantic>=2.11.8",
    "pytubefix>=9.5.1",
    "uvicorn>=0.35.0",
    "youtube-search>=2.1.2",
]
