[project]
name = "processing-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.117.1",
    "ffmpeg-python>=0.2.0",
    "pytubefix>=9.5.1",
    "uvicorn>=0.37.0",
]
