[project]
name = "discord-api-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "discord>=2.3.2",
    "discord-py[voice]>=2.6.3",
    "dotenv>=0.9.9",
    "requests>=2.32.5",
]
